language: cpp

compiler:
  - gcc

before_script:
  - sudo apt-get -y install python-software-properties
  - echo yes | sudo add-apt-repository ppa:smspillaz/cmake-2.8.12
  - sudo apt-get update -q
  - sudo apt-get -y install cmake gfortran gcc doxygen libboost-graph-dev libboost-filesystem-dev libboost-serialization-dev libatlas-base-dev libblas-dev libgmp3-dev libcppunit-dev libpcre3-dev python-matplotlib  python-numpy  python-scipy python-dev python-py make g++ git gccxml python-pygccxml python-lxml swig2.0
  - ./Build/ci-scripts/gcc-release-build $TRAVIS_BUILD_DIR libatlas
  - cd $TRAVIS_BUILD_DIR/build-dir

script:
  - time make -ik VERBOSE=1
