sudo: required

services:
  - docker

env:
  - TASK=siconos_fedora_latest
  - TASK=siconos_gcc_asan
  - TASK=siconos_gcc_asan_latest
  - TASK=siconos_debian_mechanisms
  - TASK=siconos_ubuntu_15_10
  
before_install:
  - CI/before_install.sh

before_script:
  - mkdir -p build
  - cd build

script:
  - ../CI/driver.py --run --root-dir=.. --task=$TASK
