#
# this travis config is also used with jenkins
#
sudo: required

service: docker

language: python

matrix:
  include:
    - env:
        - TASK=siconos_default:docker=false:distrib=ubuntu,14.04:targets=all,
        - CXX=g++-4.9
        - CC=gcc-4.9
        - FC=gfortran-4.9
        
      os: linux
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test

          packages:
            - libboost-dev
            - libgmp-dev
            - swig
            - libcppunit-dev
            - libblas-dev
            - liblapack-dev
            - libatlas-base-dev
            - libatlas-dev
            - g++-4.9
            - gfortran-4.9
    - env:
      - TASK=siconos_openblas_lapacke

      
before_script:
  - mkdir -p build
  - cd build

script:
  - if test "$TRAVIS" = true; then
      ../CI/driver.py --run --root-dir=.. --task=$TASK;
    else
      ../CI/driver.py --run --root-dir=..;
    fi
