#
# this travis config is also used with jenkins
#
sudo: required

service: docker

before_install:
    - CI/before_install.sh

matrix:
  include:

    - env: TYPE=travis
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3

          packages:
            - blas
            - lapack
            - cmake
            - cmake-data
            - libboost-dev
            - libgmp-dev
            - swig
            - libcppunit-dev
            - libblas-dev
            - liblapack-dev
            - libatlas-base-dev
            - libatlas-dev
            - python
            - python-dev
            - python-lxml
            - python-pytest
            - python-scipy
            - python-matplotlib
    - env:
        TASK=siconos_default:docker=false:distrib=ubuntu,14.04:targets=all,
      addons:
        apt:
          packages:
            - g++-4.9
            - gfortran-4.9
    - env:
      - TYPE=docker
      - TASK=siconos_openblas_lapacke

matrix:
  exclude:
    env:
      - TYPE=travis
      - TYPE=docker
      
before_script:
  - mkdir -p build
  - cd build
  
script:
  - if test "$TRAVIS" = true; then
      ../CI/driver.py --run --root-dir=.. --task=$TASK;
    else
      ../CI/driver.py --run --root-dir=..;
    fi
