#
# this travis config is also used with jenkins
#
sudo: required

env:
  

matrix:
  include:
    - service: docker
      env: TASK=ubuntu_14_04
    - service: docker
      env: TASK=openblas_lapacke

  
before_install:
  - CI/before_install.sh

before_script:
  - mkdir -p build
  - cd build

script:
  - if test "$TRAVIS" = true; then
      ../CI/driver.py --run --root-dir=.. --task=siconos_$TASK;
    else
      ../CI/driver.py --run --root-dir=..;
    fi
