#
# this travis config is also used with jenkins
#
sudo: required

service: docker

language: python

python: 3.6

matrix:
  include:
    - env: TASK=default:docker=true:distrib=ubuntu,16.04:targets=docker-build,docker-ctest:make_args=-j,
    - env: TASK=siconos_ubuntu_15_04
    - env: TASK=siconos_ubuntu_16_04
    - env: TASK=siconos_ubuntu_17_04
    - env: TASK=siconos_ubuntu_17_10
    - env: TASK=siconos_debian_latest
    - env: TASK=siconos_fedora_latest
    - env:
        - TASK=siconos_default:docker=false:distrib=ubuntu,14.04:targets=all,test
        - CXX=g++-7.2
        - CC=gcc-7.2
        - FC=gfortran-7.2
        
      os: linux
      python: "2.7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test

          packages:
            - libboost-dev
            - libgmp-dev
            - swig
            - libcppunit-dev
            - libblas-dev
            - liblapack-dev
            - libatlas-base-dev
            - libatlas-dev
            - g++-4.9
            - gfortran-4.9
    
before_script:
  - case $TASK in
      *docker=false*)
        pip install lxml;
        pip install scipy
        ;;
      *)
        pip install pyyaml
        ;;
    esac
  - mkdir -p build
  - cd build

script:
  - if test "$TRAVIS" = true; then
      ../CI/driver.py --run --root-dir=.. --task=$TASK;
    else
      ../CI/driver.py --run --root-dir=..;
    fi


mksenv: hello
