sudo: required

services:
  - docker

language: cpp

compiler:
  - gcc

before_script:
  # notes : here we only need to install python-yaml (for docker spec parsing), cmake/ctest and make
  # siconos packages are managed in siconos.yml
  # DOCKER_TEMPLATES contains the list (comma separated) of packages to install
  - sudo rm -vf /var/lib/apt/lists/*
  - sudo apt-get -o Acquire::CompressionTypes::Order::=bz2 update
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository ppa:smspillaz/cmake-2.8.12 -y
  - sudo add-apt-repository ppa:teward/swig3.0 -y
  - sudo apt-get update -qq
  - sudo apt-get purge cmake -qq
  - sudo apt-get -y install cmake make python-yaml
  - sudo free -m
  - mkdir -p build
  - cd build
  
script:
  - cmake -DMODE=Continuous -DCI_CONFIG=default -DWITH_DOCKER=1 -DDOCKER_TEMPLATES=siconos-gcc -DDOCKER_DISTRIB=ubuntu:14.04 ..
  - make docker-build
  - travis_wait make docker-ctest
