#
# this travis config is also used in Jenkins
#


sudo: required

services:
  - docker

env:
  - TRAVIS_TASK=siconos_fedora_latest
  - TRAVIS_TASK=siconos_gcc_asan
  - TRAVIS_TASK=siconos_gcc_asan_latest
  - TRAVIS_TASK=siconos_debian_mechanisms
  - TRAVIS_TASK=siconos_ubuntu_15_10
  
before_install:
  - CI/before_install.sh

before_script:
  - mkdir -p build
  - cd build

script:
  - ["$TRAVIS" = true] && ../CI/driver.py --run --root-dir=.. --task=$TRAVIS_TASK || \
    ../CI/driver.py --run --root-dir=..
