#
# this travis config is also used with jenkins
#
sudo: required

service: docker

before_install:
  - CI/before_install.sh

env:
  - TASK=siconos_default:docker=false:distrib=ubuntu,14.04
  - TASK=siconos_openblas_lapacke

before_script:
  - mkdir -p build
  - cd build
  - case $TASK in
       *docker=false*)
         ../CI/driver.py --run --root-dir=.. --task=$TASK --print=script > /tmp/install_pkgs
         chmod 755 /tmp/install_pkgs
         cat /tmp/install_pkgs
         /tmp/install_pkgs
         ;;
    esac
       

  
script:
  - if test "$TRAVIS" = true; then
      ../CI/driver.py --run --root-dir=.. --task=$TASK;
    else
      ../CI/driver.py --run --root-dir=..;
    fi
