#
# use mksenv --distrib=<distrib> --pkgs=pkg1,pkg2,pkg3,... \
#     --split=[true,false] <thisfile.yml> [--docker,--script]
#

##############################################################################
wildcard: any

match:
  ubuntu: debian
##############################################################################
installer:
  any:
    fedora: dnf --setopt=deltarpm=false install -y
    debian: apt-get install -y --force-yes

updater:
  any:
    debian-sid: printf "deb http://llvm.org/apt/unstable/ llvm-toolchain-3.8 main\ndeb-src http://llvm.org/apt/unstable/ llvm-toolchain-3.8 main" >> /etc/apt/sources.list && apt-get update -y
    debian-jessie: printf "deb http://llvm.org/apt/jessie/ llvm-toolchain-jessie-3.8 main\ndeb-src http://llvm.org/apt/jessie/ llvm-toolchain-jessie-3.8 main" >> /etc/apt/sources.list && apt-get update -y
    debian: apt-get update -y
    ubuntu-15.10: printf "deb http://ppa.launchpad.net/oli-huber/siconos/ubuntu wily main\ndeb-src http://ppa.launchpad.net/oli-huber/siconos/ubuntu wily main" >> /etc/apt/sources.list && apt-get update -y

##############################################################################
env:
  clang-3.8:
    any:
      - CC=/usr/bin/clang-3.8
      - CXX=/usr/bin/clang++-3.8
      - OMPI_CC=/usr/bin/clang-3.8
      - OMPI_CXX=/usr/bin/clang++-3.8
      - LLVM_SYMBOLIZER=/usr/lib/llvm-3.8/bin/llvm-symbolizer
      - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-3.8/bin/llvm-symbolizer
      - MSAN_SYMBOLIZER_PATH=/usr/lib/llvm-3.8/bin/llvm-symbolizer

  clang:
    any:
      - CC=/usr/bin/clang
      - CXX=/usr/bin/clang++
      - OMPI_CC=/usr/bin/clang
      - OMPI_CXX=/usr/bin/clang++

  mumps:
    any:
      - CC=mpicc
      - FC=mpif90
      - CXX=mpicxx

# see http://pages.cs.wisc.edu/~ferris/path/LICENSE
  path:
    any:
      - PATH_LICENSE_STRING="3413119131&Courtesy&&&USR&54784&12_1_2016&1000&PATH&GEN&31_12_2017&0_0_0&5000&0_0"

##############################################################################
pkgs:

  build-base:
    any:
      - make
      - cmake
      - boost
      - gmp
      - swig
      - cppunit

  python-env:
    debian:
      - python
      - python-dev
      - python-lxml
      - python-pytest
      - python-scipy
      - python-matplotlib
    fedora:
      - python
      - python-devel
      - python-lxml
      - pytest
      - scipy
      - python-matplotlib

  python3-env:
    debian:
      - python3
      - python3-dev
      - libpython3-dev
      - python3-lxml
      - python3-pytest
      - python3-scipy
      - python3-matplotlib
    fedora:
      - python3
      - python3-devel
      - python3-lxml
      - python3-scipy
      - python3-pytest
      - python3-scipy
      - python3-matplotlib

  profiling:
    debian:
      - valgrind
      - python-dbg
    fedora:
      - valgrind
      - python-debuginfo

  lpsolve:
    debian:
      - lp-solve
      - liblpsolve55-dev
    fedora:
      - lpsolve-devel

  cmake:
    ubuntu-12.04:
       - python-software-properties
       - cmake-2.8.12
       - python-matplotlib


  cmake-2.8.12:
    ubuntu-12.04:
      command:
        add-apt-repository ppa:smspillaz/cmake-2.8.12 -y &&
        add-apt-repository ppa:teward/swig3.0 -y &&
        add-apt-repository ppa:boost-latest/ppa -y &&
        apt-get update -qq &&
        apt-get purge cmake -qq &&
        apt-get -y install cmake

  gfortran:
    fedora: gcc-gfortran

  gnu-c++:
    debian: g++
    fedora: gcc-c++

  boost:
    debian: libboost-dev
    fedora: boost-devel

  serialization:
    debian:
      libboost-filesystem-dev
      libboost-serialization-dev
    fedora:
      boost-filesystem
      boost-serialization

  gmp:
    debian: libgmp-dev
    fedora: gmp-devel


  cppunit:
    debian:
      - libcppunit-dev

    fedora: 
      - cppunit
      - cppunit-devel

  hdf5:
    fedora: hdf5-devel
    debian: libhdf5-dev

  h5py:
    fedora: h5py
    debian: python-h5py

  h5py3:
    any: python3-h5py

  openblas-lapacke:
    debian:
      - libopenblas-dev
      - liblapacke-dev
    fedora:
      - openblas-devel
      - lapack-devel

  atlas-lapack:
    debian:
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - libatlas-dev

    fedora:
      - blas
      - blas-devel
      - atlas-devel

  oce:
    debian:
      - liboce-foundation-dev
      - liboce-modeling-dev
      - liboce-ocaf-dev
      - liboce-visualization-dev
      - oce-draw

    fedora:

  mumps:
    debian-7.8:
      - libopenmpi-dev
      - openssh-client
      - libscalapack-mpi-dev
      - libscotchmetis-dev
      - libmumps-dev

    debian:
      - libopenmpi-dev
      - openssh-client
      - libscalapack-mpi-dev
      - libmetis-dev
      - libmumps-dev

    fedora:
      - ptscotch-openmpi 
      - ptscotch-openmpi-devel 
      - blacs-openmpi-devel
      - openmpi-devel
      - scalapack-openmpi
      - MUMPS-openmpi-devel
      - environment-modules

  bullet:
    debian:
      - libbullet-dev

  umfpack:
    debian:
      - libsuitesparse-dev
    fedora:
      - suitesparse-devel

  asan:
    fedora:
      - libasan
      - libubsan

  xz:
    debian:
      - xz-utils

  fclib:
    any:
      command: svn checkout svn://scm.gforge.inria.fr/svnroot/fclib/ &&
               cd fclib/trunk &&
               cmake . -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release &&
               make &&
               make install

  clang:
    debian-jessie:
      - clang-3.8
# Don't worry, this is a hack to get cppunit to work with clang on ubuntu 15.10, because the system cppunit
# has been compiled with a different string impl ...
  cppunit_clang:
    ubuntu-15.10:
      command:  wget http://siconos.gforge.inria.fr/build-42/cppunit-clang-ubuntu-15.10.tar.xz &&
                tar xJf cppunit-clang-ubuntu-15.10.tar.xz --strip-components=1 -C /usr/lib/x86_64-linux-gnu/

# this is for msan. It also contains the so files for cppunit compiled with msan
  libcxx_msan:
    any:
      command: wget http://siconos.gforge.inria.fr/build-42/libcxx_msan-clang-3.6.tar.xz &&
               tar xJf libcxx_msan-clang-3.6.tar.xz -C /

# dummy target
  cfi:
    any:
      command: mkdir /tmp/clang && ln -s /usr/bin/ld.gold /tmp/clang/ld

  path:
    debian:
      command: wget -O - https://github.com/ampl/pathlib/raw/master/lib/linux64/libpath47.so > /usr/lib/x86_64-linux-gnu/libpath47.so
    fedora:
      command: wget -O - https://github.com/ampl/pathlib/raw/master/lib/linux64/libpath47.so > /usr/lib64/libpath47.so
