#
# use mksenv --distrib=<distrib> --pkgs=pkg1,pkg2,pkg3,... \
#     --split=[true,false] <thisfile.yml> [--docker,--script]
#

##############################################################################
wildcard: any

match:
  ubuntu: debian
##############################################################################
installer:
  any:
    fedora: dnf --setopt=deltarpm=false install -y
    debian: apt-get install -y

updater:
  any:
    debian: apt-get update -y
##############################################################################
env:
  clang-3.7:
    any:
      - CC=/usr/bin/clang-3.7
      - CXX=/usr/bin/clang++-3.7
      - OMPI_CC=/usr/bin/clang-3.7
      - OMPI_CXX=/usr/bin/clang++-3.7

  clang:
    any:
      - CC=/usr/bin/clang
      - CXX=/usr/bin/clang++
      - OMPI_CC=/usr/bin/clang
      - OMPI_CXX=/usr/bin/clang++

  mumps:
    any:
      - CC=mpicc
      - FC=mpif90
      - CXX=mpicxx

##############################################################################
pkgs:

  build-base:
    any:
      - make
      - cmake 
      - boost
      - gmp
      - python-env
      - swig
      - cppunit

  lpsolve:
    debian:
      - lp-solve
      - liblpsolve55-dev
    fedora:
      - lpsolve-devel

  python-env:
    debian:
      - python
      - python-dev
      - python-lxml
      - python-pytest
      - python-scipy
      - python-matplotlib
    fedora:
      - python
      - python-devel
      - python-lxml
      - pytest
      - scipy
      - python-matplotlib

  cmake:
    ubuntu-12.04:
       - python-software-properties
       - cmake-2.8.12
       - python-matplotlib


  cmake-2.8.12:
    ubuntu-12.04:
      command:
        add-apt-repository ppa:smspillaz/cmake-2.8.12 -y &&
        add-apt-repository ppa:teward/swig3.0 -y &&
        add-apt-repository ppa:boost-latest/ppa -y &&
        apt-get update -qq &&
        apt-get purge cmake -qq &&
        apt-get -y install cmake

  gfortran:
    fedora: gcc-gfortran

  gnu-c++:
    debian: g++
    fedora: gcc-c++
  
  boost:
    debian: libboost-dev
    fedora: boost-devel

  serialization:
    debian:
      libboost-filesystem-dev
      libboost-serialization-dev

  gmp:
    debian: libgmp-dev
    fedora: gmp-devel


  cppunit:
    debian:
      - libcppunit-dev

    fedora: 
      - cppunit
      - cppunit-devel

  hdf5:
    fedora: hdf5-devel
    debian: libhdf5-dev

  h5py:
    fedora: h5py
    debian: python-h5py

  openblas-lapacke:
    debian:
      - libopenblas-dev
      - liblapacke-dev
    fedora:
      - openblas-devel
      - lapack-devel

  atlas-lapack:
    debian:
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - libatlas-dev

    fedora:
      - blas
      - blas-devel
      - atlas-devel

  oce:
    debian:
      - liboce-foundation-dev
      - liboce-modeling-dev
      - liboce-ocaf-dev
      - liboce-visualization-dev
      - oce-draw

    fedora:

  mumps:
    debian-7.8:
      - libopenmpi-dev
      - openssh-client
      - libscalapack-mpi-dev
      - libscotchmetis-dev
      - libmumps-dev

    debian:
      - libopenmpi-dev
      - openssh-client
      - libscalapack-mpi-dev
      - libmetis-dev
      - libmumps-dev

    fedora:
      - ptscotch-openmpi 
      - ptscotch-openmpi-devel 
      - blacs-openmpi-devel
      - openmpi-devel
      - scalapack-openmpi
      - MUMPS-openmpi-devel
      - environment-modules

  bullet:
    debian:
      - libbullet-dev


  asan:
    fedora:
      - libasan
      - libubsan

  xz:
    debian:
      - xz-utils

  fclib:
    any:
      command: svn checkout svn://scm.gforge.inria.fr/svnroot/fclib/ &&
               cd fclib/trunk &&
               cmake . -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release &&
               make &&
               make install

# Don't worry, this is a hack to get cppunit to work with clang on ubuntu 15.10, because the system cppunit
# has been compiled with a different string impl ...
  cppunit_clang:
    ubuntu-15.10:
      command:  wget http://siconos.gforge.inria.fr/build-42/cppunit-clang-ubuntu-15.10.tar.xz &&
                tar xJf cppunit-clang-ubuntu-15.10.tar.xz --strip-components=1 -C /usr/lib/x86_64-linux-gnu/

# this is for msan. It also contains the so files for cppunit compiled with msan
  libcxx_msan:
    any:
      command: wget http://siconos.gforge.inria.fr/build-42/libcxx_msan-clang-3.6.tar.xz &&
               tar xJf libcxx_msan-clang-3.6.tar.xz -C /
